### ISSUE TITLE
What is the purpose of `options` here?

### ISSUE THREAD

**Issue by purplecabbage** [adobe/generator-aio-console#32]
https://github.com/adobe/generator-aio-console/blob/5d5847e00127f0817c95aba508dcc52544ad3151/lib/console-cli.js#L45

**Comment by meryllblanchet** [comment]
Let's ask @shazron

**Comment by moritzraho** [comment]
For now there is no reason to this, it's a left over from something that got implemented differently, will remove as part of #24
